=== JLGG4556/EjerciciosLMSGI2/apuntes/apuntesdtd/DTD/practica examen/examenapunte.dtd
<!ELEMENT tienda (sillas, ofertas)>
<!ELEMENT sillas (silla+)><!-- Se usa el +-->
<!ELEMENT ofertas (oferta*)><!--Se usa el *-->
<!ELEMENT silla (nombre, precio, (existencias | agotado?))><!--Secuencia de elementos con optatividad--> <!--Se usa el *-->
<!ELEMENT nombre (#PCDATA)> <!-- Esto es un elemento mixito-->
<!ELEMENT existencias (#PCDATA)>
<!ELEMENT precio EMPTY>
<!ELEMENT agotado EMPTY><!--Se usa el EMPTY elemento con contenido vacio-->
<!ELEMENT oferta (#PCDATA | exclusiva)*>


<!ELEMENT exclusiva ANY>
<!--Se utilizan los tres caracteres que pueden tomar los atributos IMPLIED REQUIRED FIXED-->
<!ATTLIST tienda direccion CDATA #IMPLIED
                    nombre CDATA #REQUIRED
                    telefono CDATA #FIXED "555555555">

<!-- Se usa el atributto ID IDREF y IDREFS-->
<!ATTLIST silla codigo ID #REQUIRED
                    materiales (cristal | madera | diamante) "cristal">
<!ATTLIST exclusiva codigosilla IDREF #REQUIRED
                    sillamixta IDREFS #IMPLIED>

<!ENTITY % atributocoste "coste CDATA #IMPLIED">
<!ATTLIST precio %atributocoste;>
<!ATTLIST oferta %atributocoste;>
<!ENTITY Montada "premontada">

=== JLGG4556/EjerciciosLMSGI2/apuntes/apuntesdtd/DTD/practica examen/examenapunte.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "examenapunte.dtd">

<tienda direccion="calle sillon" nombre="mueblesmauricio" telefono="555555555">

<sillas>

    <silla codigo="cri" materiales="cristal">
        <nombre>sillacristalium</nombre>
        <precio coste="130€"/>
        <agotado />
    </silla>

    <silla codigo="dia">
        <nombre>supersilladia %Montada;</nombre>
        <precio coste="40€"/>
        <existencias>12</existencias>

    </silla>

</sillas>

<ofertas>

    <oferta coste="45">-30%
        <exclusiva codigosilla="cri" sillamixta="cri dia"></exclusiva>
    </oferta>

</ofertas>

</tienda>
