=== JLGG4556/EjerciciosLMSGI2/Examenes/DTD/Examen de DTD ya terminado/juegosderol.dtd
<!ELEMENT Juego (personajes, villanos, movimientosespeciales?)>
<!ELEMENT personajes (personaje*)>
<!ELEMENT villanos (villano+)>
<!ELEMENT personaje (nombre, nivel, movimiento+, (vivo | muerto?))>
<!ELEMENT villano (nombre, nivel, movimiento+, (vivo | muerto?))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT movimiento (#PCDATA)>
<!ELEMENT vivo EMPTY>
<!ELEMENT muerto EMPTY>

<!ELEMENT movimientosespeciales (#PCDATA | movimientoespecial)*>
<!ELEMENT movimientoespecial ANY>

<!ATTLIST personaje numero CDATA #IMPLIED
                    mote CDATA #REQUIRED
                    potenciabase CDATA #FIXED "50">

<!ATTLIST villano estado ID #REQUIRED
                        estados (encubierto | atrapado | descubierto) "encubierto">
<!ATTLIST movimientoespecial SuperataqueEnEstado IDREF #REQUIRED
                        superataques IDREFS #IMPLIED>

<!ENTITY % gasto "gasto CDATA #IMPLIED">
<!ATTLIST  movimientosespeciales %gasto;>
<!ATTLIST movimiento %gasto;>

=== JLGG4556/EjerciciosLMSGI2/Examenes/DTD/Examen de DTD ya terminado/juegosderol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Juego SYSTEM "juegosderol.dtd">

<Juego>
    <personajes>

        <personaje numero="1" mote="Mufasa" potenciabase="50">
            <nombre>Ambrosio de la sierra</nombre>
            <nivel>34</nivel>
            <movimiento gasto="10PP">Sanacion</movimiento>
            <vivo />
        </personaje>

        <personaje numero="1" mote="Musanpe" potenciabase="50">
            <nombre>Adelio Gomez</nombre>
            <nivel>30</nivel>
            <movimiento gasto="10PP">Lanzallamas</movimiento>
            <muerto />
        </personaje>

    </personajes>

    <villanos>

       <villano estado="encubierto">
            <nombre>Ebaristo de los campos</nombre>
            <nivel>45</nivel>
            <movimiento gasto="10PP">Sombra maligna chunga</movimiento>
            <vivo />
       </villano>

    </villanos>

<movimientosespeciales gasto="45PP">
    <movimientoespecial SuperataqueEnEstado="encubierto">Super</movimientoespecial>
</movimientosespeciales>

</Juego>
